### ISSUE TITLE
Centos 6.4 Build issue

### ISSUE THREAD

**Issue by vdharashive** [openss7/openss7#1]
make  install-data-hook
make[4]: Entering directory `/root/Download/openss7-1.1.7.20131209/build'
/bin/sh ../scripts/install_initd -v /etc/rc.d/init.d/specfs
 /usr/lib/lsb/install_initd /etc/rc.d/init.d/specfs
/bin/sh ../scripts/install_initd -v /etc/rc.d/init.d/streams
 /usr/lib/lsb/install_initd /etc/rc.d/init.d/streams
/bin/sh ../scripts/install_initd -v /etc/rc.d/init.d/openss7
 /usr/lib/lsb/install_initd /etc/rc.d/init.d/openss7
/bin/sh ../scripts/install_initd -v /etc/rc.d/init.d/strace
 /usr/lib/lsb/install_initd /etc/rc.d/init.d/strace
/bin/sh ../scripts/install_initd -v /etc/rc.d/init.d/strerr
 /usr/lib/lsb/install_initd /etc/rc.d/init.d/strerr
/bin/sh /root/Download/openss7-1.1.7.20131209/scripts/install-sh -d /etc/nslconfig.d
/usr/bin/install -c -m 644 ../src/util/sysconfig/netconfig /etc/nslconfig.d/openss7
/bin/sh /root/Download/openss7-1.1.7.20131209/scripts/install-sh -d /etc/sock2path.d
/usr/bin/install -c -m 644 ../src/util/sysconfig/sock2path /etc/sock2path.d/openss7
/bin/sh /root/Download/openss7-1.1.7.20131209/scripts/install-sh -d /etc/snmp/snmp.d
/usr/bin/install -c -m 644 ../src/util/sysconfig/snmp /etc/snmp/snmp.d/01openss7
gawk -f /root/Download/openss7-1.1.7.20131209/scripts/openss7-modules -- -v 2 --style=redhat -c  -b  -k 2.6.32-279.el6.x86_64 --add-modules
openss7-modules: I: t: depmod,    depmod does not support -E option
openss7-modules: E: o: one and only one KVERSION permitted for --add-modules
openss7-modules:
  $Id: openss7-modules,v 1.1.2.11 2011-09-20 09:51:33 brian Exp $
Usage:
  [awk -f ]openss7-modules -- [options] [mode] [KERNEL ...]
  [awk -f ]openss7-modules -- -h, --help
  [awk -f ]openss7-modules -- -V, --version
  [awk -f ]openss7-modules -- -C, --copying
openss7-modules: E: o: one and only one KVERSION permitted for --add-modules
openss7-modules: E: errs = 1
make[4]: *** [post-updates] Error 2
make[4]: Leaving directory`/root/Download/openss7-1.1.7.20131209/build'
make[3]: **\* [install-data-am] Error 2
make[3]: Leaving directory `/root/Download/openss7-1.1.7.20131209/build'
make[2]: *** [install-am] Error 2
make[2]: Leaving directory`/root/Download/openss7-1.1.7.20131209/build'
make[1]: **\* [install-recursive] Error 1
make[1]: Leaving directory `/root/Download/openss7-1.1.7.20131209/build'
make: **\* [install] Error 2

**Comment by henrycaga** [comment]
Hi.


Im having the same trouble like this issue.
My error after running "make install" is :
openss7-modules: E: o: one and only one KVERSION permitted for --add-modules

im running CentOS 6.4:
# uname -r
2.6.32-504.12.2.el6.i686

2nd question is, Im also registered in openss7.org under the username of henryc
but i dont know what package and rpm file should i download. when i tried to run rpm -ihv openss7-(some_rpm_file_here).rpm, after entering my username and password, it says "Authorization failed" pls help. thank you

-henry

**Comment by kannanpuv** [comment]
Hi Brian,
    Getting the below error when tried with openss7-1.1.7.20131207...

Permission Issue : 
Loading Special Shadow Filesystem (specfs): FATAL: Error inserting specfs (/lib/modules/2.6.32-504.12.2.el6.i686/extra/openss7/specfs.ko): Permission denied
FATAL: Error running install command for specfs
                                                           [FAILED]

System Configurations :
OS & Kernel  : CentOS 6.4 with kernel 2.6.32-504.16.2.el6.x86_64...
OpenSS7 Download Link :  http://www.openss7.org/download.html 

If tried with ./configure --disable-specfs-lock
Tried below steps :
./openss7 start
./specfs start
./streams start
specfs got started... but with streams start getting the below error 

kernel:Kernel panic - not syncing: Fatal exception

Got stuck at this point.... It would be helpful, if you could suggest the way to resolve it...

Also getting the below error on make install :
o: one and only one KVERSION permitted for --add-modules openss7-modules: E: errs = 1

--
Thanks
Kannan

**Comment by xiangyux** [comment]
Hi Brain,
I am working on a project using the openss7 with Christophe Nolibos, who is one of the contributors of openss7. I have the same problem of issue1. I am trying to download the pre-built CentOS6 rpm from the OpenSS7 Repository. I have registered as xiangyuxu, but I don't have any access to internet on any Linux server, could you propose me another way to download the rpm?

Best regards,
Thanks!
Xiangyu

**Comment by bbidulock** [comment]
Until I manage the next release of (http://www.unexicon.com/)[unexicon], installing binary packages will require access to the internet from a linux box.

**Comment by xiangyux** [comment]
Thanks for your response. I am wondering that if the bin package has been built for CentOS6, could you tell me what was the compilation environment? On which OS was it built? Is there any modifications to be done of the files in the package of source "openss7-1.1.7.20131207.tar.xz" ?

Thanks.
Xiangyu

**Comment by yatyanng** [comment]
In the script scripts/openss7-modules, I change 
from 
longopts["kversion"      ] = "k:" ;
to
longopts["kernels"      ] = "k:" ;

Then, it works.

**Comment by aguilasainz** [comment]
Hi there @bbidulock I tried your suggestions for CentOS, but no luck:

[ss7@localhost build]$ make rpms
make: *** No rule to make target `rpms'.  Stop.
