### ISSUE TITLE
Fedora 15 fails make install

### ISSUE THREAD

**Issue by johntaves** [openss7/openss7#10]
/usr/bin/mandb: invalid option -- 'v'

**Comment by bbidulock** [comment]
make -k install

or

ln -s /usr/bin/true mandb
export PATH=".:$PATH"
make install

**Comment by johntaves** [comment]
OK, after disabling mandb the make completes without error. I am now able to compile and link.

This is Fedora 15, openss7-1.1.7.20131207

t_open("/dev/streams/xtiso/cots",O_RDWD,NULL) fails with -1 and t_error says: "System error".

I see no /dev/streams folder.
lsmod does not list streams or specfs.

**Comment by bbidulock** [comment]
Two things:

1. The reason that /dev/streams does not appear is because the tarball version that you are using is locked so the specfs module will fail to load.  I told you that I had not had time to remove the locking and that the only away around this for now is to use an openss7.org repository version.

2. There is no /dev/streams/xtiso/cots device.  That is a OSF/1 device.  The equivalent driver in Linux Fast-STREAMS is the "inet" driver.  This can be opened with old character device nodes "/dev/tcp", "/dev/inet/tcp" or, preferrably, "/dev/streams/inet/tcp".  But, of course, this will not work until you address the first thing.

**Comment by johntaves** [comment]
Sorry for being thick, but I don't see where I was told the most recent version on openss7/download.html is locked and therefore shouldn't be used.

I don't know what you mean by use a repository version. I see a version openss7-1.1.7.20131209 on this github thing.

I registered as johntaves.

**Comment by bbidulock** [comment]
OK, I lied.  Is seems like I added a configure option to disable locking: just configure with --disable-specfs-lock to get around the locking.  So, if you compile that way there is just the second thing.

**Comment by johntaves** [comment]
I configured with that option and make, make install seemed to run without errors.

lsmod does not show the stream module, or the specfs module.
I see no /dev/streams folder.
t_open("/dev/streams/inet/tcp",O_RDWR,NULL) returns -1 and t_error returns "System error".

**Comment by bbidulock** [comment]
You need to start the specfs and streams subsystems  (something like sudo /etc/init.d/specfs start; sudo /etc/init.d/streams start) if they didn't start during installation.  If they succeed 'mount' command should show specfs filesystem mounted on /dev/streams.  If they fail, look in the logs (/var/log/messages or such) for error messages.  If succeed succeed, try your program again.

**Comment by bbidulock** [comment]
Did you manage to start the specfs and streams subsystems?

**Comment by johntaves** [comment]
Yes, and the t_open call returns success.

**Comment by bbidulock** [comment]
Why not try doing the same thing you did with FC15?  It might work, it might not.  I'm sorry but it is not a very good use of my time to attempt non-commercial support of a deprecated kernel.

**Comment by johntaves** [comment]
However, after I wrote that t_open call returns success, I rebooted the computer and it fails to start properly now.

I returned to a previous version (these are virtual machines) that boots fine, then did:
./configure --disable-specfs-lock; make, then as root make install. Then reboot, and it fails to bring up the X windows or give me a text login prompt.

I booted with "single" and got a prompt and did systemctl disable openss7.service. That returns a bunch of "unknown lvalue ...." lines and a subsequent reboot still fails.

I booted with "single" again and did make uninstall and now it boots.

Keep in mind that after I do make install and start the specfs/streams subsystems the t_open call returned success, but now the computer won't boot.

**Comment by bbidulock** [comment]
Ok, sounds like some problem with module initialization.  I recall fixing a problem like that some time ago: what version are you running now?  Are you using current git master branch?  If not, clone and compile from current git and try again.

**Comment by johntaves** [comment]
I used the latest tarball I could find as stated above openss7-1.1.7.20131207.

I picked Fedora 15 because it was a 2.x kernel and because your documentation says it works. I just want a working version and I have no emotional attachment to any particular distribution or version. Can you tell me the shortest path to getting this to work?

(I will worry about getting the 2.6.12.1 kernel version working after I succeed at getting some version to work, any version.)

Thanks,

**Comment by bbidulock** [comment]
See my comment here: https://github.com/openss7/openss7/issues/6#issuecomment-67721319

The quickest way to get this working is to follow the instructions at http://www.openss7.org/repos.html for a bare-metal install of rpms for RHEL/CentOS 6.4.
