### ISSUE TITLE
CentOS 6.4

### ISSUE THREAD

**Issue by henrycaga** [openss7/openss7#11]
Hi.

Im having the same trouble like issue #1 . (i also place a comment there)

configure has no errors. i run the following commands :
make V=0
make check

My error is after running "make install" :
openss7-modules: E: o: one and only one KVERSION permitted for --add-modules

im running CentOS 6.4:
uname -r
2.6.32-504.12.2.el6.i686

2nd question is, Im also registered in openss7.org under the username of henryc
but i dont know what package and rpm file should i download. what is the exact rpm that i should use? when i tried to run rpm -ihv openss7-(some_rpm_file_here).rpm, after entering my username and password, it says "Authorization failed" pls help. thank you

-henry

**Comment by bbidulock** [comment]
Henry,

I have focused efforts fairly exclusivly on Arch Linux development.  Since those issues, I have put up a an [openss7-git](https://aur.archlinux.org/pkgbase/openss7-git/) package on [AUR](https://aur.archlinux.org/) that builds and installs.  Test suites ran without crashing for linux-lts 3.14 kernel (although there were some failed test cases for SCTP at last report, but that might be fixed).  Test suites for the linux 3.18 kernel crashed (again a problem with SCTP routing that may be fixed).  Haven't tried to build for 3.19.2 kernel yet.  If you are familiar with Arch Linux, that is the best way to give it a whirl (and avoid using an ancient CentOS release).

The issue with the openss7 repository is that those copies were license locked years ago.  I can go in and unrestrict your access so that you can see and install the 6.4 rpms, but RH has been breaking its own kernel ABIs in recent 6-series kernels and it still may not work.

I'm still spinning up the [unexicon](http://www.unexicon.com/) distro based on Arch Linux, but it will eventually have openss7 (and others) pre-installed in a host/guest system for NFV with various VNF modules.  So I would rather deal with issues on Arch going forward.

Let me know if you want to push forward with CentOS or feel confident with loading up Arch.

Brian

**Comment by henrycaga** [comment]
Hi Brian, 

thanks for the quick response. im now going to take a look at Arch Linux. and reinstall everything. but if its possible, i still want to try it out on CentOS, its been almost a week since i've tried to make this thing work, i've been to Ubuntu 14.04, then move to CentOS 6.4, and now, to Arch Linux. but thats ok, but can i still have access to the file in order to try my CentOS flavor? thanks a lot and more power sir.

Henry

**Comment by bbidulock** [comment]
You should be able to see RHEL 6 now.

**Comment by henrycaga** [comment]
Cool, thanks a lot sir! after this, i will still switch to Arch Linux. thank you so much.

**Comment by henrycaga** [comment]
hi sir brian, now im trying to install openss7 in arch linux. but having some error while building openss7 package. 

i already installed gcc-gcj. In gjdoc, theres a lot of warning but installation was successful.
however, when im trying to build openss7, it shows an error something like javax error: "header used out of sequence"

is it because of the gjdoc installation? any tips or ideas on this to build openss7 successfully? thanks a lot.

Henry

**Comment by bbidulock** [comment]
Are you building from the [AUR package](https://aur.archlinux.org/pkgbase/openss7-git/)?

**Comment by henrycaga** [comment]
Hi brian, yes im building from AUR Package. Actually im using the command
yaourt openss7-git
Thanks for the reply.

**Comment by henrycaga** [comment]
any update from here sir? am i doing right? thanks
-Henry

**Comment by bbidulock** [comment]
I don't have any problems building the package and no java errors nor warnings are generated.  Possibilities: you have a bad gcj build; your JAVA_HOME environment variable is inappropriately set; you have another java runtime and build installed that is interferring with gcj.

**Comment by bbidulock** [comment]
Looks like it won't build against 3.19.2 kernel yet: some change to file pointer f_dentry field.

**Comment by henrycaga** [comment]
hi sir, actually, i downgraded my kernel to 3.14 because i cant build it on 3.19.

right now, im trying to fix it by removing jdk8 and re installing jdk7. when i was in 3.19 kernel before, i didnt get this kind of error because im using java environment 7 in 3.19. but when i downgraded to 3.14, i used the java 8 instead of 7. so, i hope this will work. and i will update this.

thank you. still waiting for update in 3.19 kernel :) thank you sir

**Comment by bbidulock** [comment]
Actually, you might be better to remove them both (jdk7 and jdk8), at least to build openss7-git.  Just about have 3.19.2 building.

**Comment by henrycaga** [comment]
now im having other errors. its been 2 weeks since i start this. maybe i should give up this time. and wait for update on openss7 at 3.19.2 kernel. :)

**Comment by bbidulock** [comment]
I'm slowly working through 3.19.2 build issues.  Unfortunately kernel developers changed a number of ridiculous things (removing macros for the sake of it).  I will let you know here once I'm done and they you can try again.

**Comment by bbidulock** [comment]
Should build against 3.19.3-3 kernel now.

**Comment by henrycaga** [comment]
Hi brian,

Thanks a lot, i'll try it again this morning. I will update this as soon as possible.

Thanks a lot
Henry

**Comment by henrycaga** [comment]
Hi Brian
it was a success. i already build and install openss7 successfully under Archlinux with kernel 3.19.3-3. Thanks a lot for all the help :)

Henry

**Comment by aguilasainz** [comment]
Hi! I've been trying to build on CentOS 6.4, and I'm having this error:  


`2 problems (2 warnings)
  GCJ      javax/jain/DeleteProviderException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/DeleteProviderException.java:57: warning: The serializable class DeleteProviderException does not declare a static final serialVersionUID field of type long
	public class DeleteProviderException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/IDNotAvailableException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/IDNotAvailableException.java:56: warning: The serializable class IDNotAvailableException does not declare a static final serialVersionUID field of type long
	public class IDNotAvailableException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/InvalidAddressException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/InvalidAddressException.java:58: warning: The serializable class InvalidAddressException does not declare a static final serialVersionUID field of type long
	public class InvalidAddressException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/InvalidArgumentException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/InvalidArgumentException.java:56: warning: The serializable class InvalidArgumentException does not declare a static final serialVersionUID field of type long
	public class InvalidArgumentException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/InvalidPathNameException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/InvalidPathNameException.java:55: warning: The serializable class InvalidPathNameException does not declare a static final serialVersionUID field of type long
	public class InvalidPathNameException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/InvalidStateException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/InvalidStateException.java:56: warning: The serializable class InvalidStateException does not declare a static final serialVersionUID field of type long
	public class InvalidStateException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/JainEvent.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/JainEvent.java:55: warning: The serializable class JainEvent does not declare a static final serialVersionUID field of type long
	public abstract class JainEvent extends java.util.EventObject implements java.io.Serializable, java.lang.Cloneable {
	                      ^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/ListenerAlreadyRegisteredException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/ListenerAlreadyRegisteredException.java:57: warning: The serializable class ListenerAlreadyRegisteredException does not declare a static final serialVersionUID field of type long
	public class ListenerAlreadyRegisteredException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/ListenerNotRegisteredException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/ListenerNotRegisteredException.java:57: warning: The serializable class ListenerNotRegisteredException does not declare a static final serialVersionUID field of type long
	public class ListenerNotRegisteredException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/MandatoryParameterNotSetException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/MandatoryParameterNotSetException.java:57: warning: The serializable class MandatoryParameterNotSetException does not declare a static final serialVersionUID field of type long
	public class MandatoryParameterNotSetException extends ParameterNotSetException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/home/ss7/ss7/build/src/java/../../../openss7-1.1.7.20131207/src/java/javax/jain/ParameterNotSetException.java:57: warning: The serializable class ParameterNotSetException does not declare a static final serialVersionUID field of type long
	public class ParameterNotSetException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^
2 problems (2 warnings)
  GCJ      javax/jain/MethodNotSupportedException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/MethodNotSupportedException.java:56: warning: The serializable class MethodNotSupportedException does not declare a static final serialVersionUID field of type long
	public class MethodNotSupportedException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/PeerUnavailableException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/PeerUnavailableException.java:68: warning: The serializable class PeerUnavailableException does not declare a static final serialVersionUID field of type long
	public class PeerUnavailableException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/PlatformException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/PlatformException.java:57: warning: The serializable class PlatformException does not declare a static final serialVersionUID field of type long
	public class PlatformException extends JainException {
	             ^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GCJ      javax/jain/VersionNotSupportedException.class
../../../openss7-1.1.7.20131207/src/java/javax/jain/VersionNotSupportedException.java:56: warning: The serializable class VersionNotSupportedException does not declare a static final serialVersionUID field of type long
	public class VersionNotSupportedException extends JainException {
	             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
1 problem (1 warning)
  GEN      javax-jain-1.1.7.20131207.jar
  GEN      javax-jain.jar
  GCJ      lib_javax_jain_la-javax-jain.lo
  GCJLD    lib-javax-jain.la
/usr/bin/ld: .libs/lib_javax_jain_la-javax-jain.o: relocation R_X86_64_32 against `__gcj_personality_v0' can not be used when making a shared object; recompile with -fPIC
.libs/lib_javax_jain_la-javax-jain.o: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[3]: *** [lib-javax-jain.la] Error 1
make[3]: Leaving directory `/home/ss7/ss7/build/src/java'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ss7/ss7/build/src/java'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ss7/ss7/build'
make: *** [all] Error 2
`

Any idea? Thanks!
