### ISSUE TITLE
install openss7

### ISSUE THREAD

**Issue by pcornill** [openss7/openss7#12]
Hi,
I would like to install a 'simple' sctp endpoint to establish an association with a test equipment.
I spent 2 days trying to install openss7 but unsucessful.
Is there a tuto that explain step by step how to install and configure?
I tried to install CentOS 6.4 then the rpm but I have a proxy and cannot figure out the way to update the package.
Please help

**Comment by bbidulock** [comment]
Until the next release of [unexicon](http://www.unexicon.com) is ready, load [archlinux](http://www.archlinux.org) and then build and install the [AUR package](https://aur.archlinux.org/packages/openss7-git).

You will then find a test program installed in /usr/lib/openss7/test-sctp_t that will run tests.  The source code for the test program is in [test-sctp_t.c](https://github.com/openss7/openss7/blob/master/src/test/test-sctp_t.c).

Ask questions sooner than later: it will save you time.

**Comment by pcornill** [comment]
Hi,Unexicon looks great. When do you think it will be ready?Would the 2013 release work for my "simple" SCTP/M2PA/M3UA test?
Ideally, if you had a VM already installed, would be awesome ;-)Thanks a lot for your great supportPierre 

Date: Sun, 31 May 2015 22:59:46 -0700
