### ISSUE TITLE
OpenSS7 sctp overflow

### ISSUE THREAD

**Issue by Badbits** [openss7/openss7#13]
Hi Brian,

I'm trying to use your library to set-up a sigtran stack, however when I try to use the sctp streams driver it crashes and when I run your supplied test-sctp it overflows ADDR.

https://gist.github.com/Badbits/a3053555741c10f6424a

Are you aware of this? I'll go back to using the linux kernel sctp stack but it just seems a little convoluted, I can see sections from where the kernels sctp module was used so I guess it's still interoperable.

Kernel: 3.18.11 x86_64.
gcc version 4.8.4

**Comment by bbidulock** [comment]
That particular program is an old test program that is no longer used.  See the autotest test suite.  The programs used by the test suite are test-sctp_n, test-sctp_n2 and test-sctp_t.  Better still, just run the validation test suite which invokes each specific test case in these suites.
