### ISSUE TITLE
trouble with test-m2ua-as

### ISSUE THREAD

**Issue by sanmaoyun** [openss7/openss7#14]
My system is ubuntu 10.04.
    When running test-m2ua-as separately under /usr/libexec/openss7,it return:

RFC 3331/ETSI TS 102 380 V1.1.1 (2004-12) - SIGnalling TRANsport - M2UA - Conformance Test Suite
Using device /dev/streams/clone/m2ua-as
Using transport /dev/streams/clone/sctp_t
Test Suite setup failed!

    The problem is that when open device /dev/streams/clone/m2ua-as,it return -1,and the errno = 6,means "No such device or address".
    Does anyone know how to resolve this problem?
    Thank you.

**Comment by sanmaoyun** [comment]
All the tests in test-m2ua_as are unfinished, right?

**Comment by bbidulock** [comment]
Only the test programs that are run by the autotest testsuite are used.  Yes, there are some test programs that are not part of the test suite (some historical, some half-baked), but there are over 5000 test cases in the formal validation suite run by autotest.
