### ISSUE TITLE
trouble building on CentOS 7

### ISSUE THREAD

**Issue by rupikum** [openss7/openss7#15]
Hi,

I have downloaded the master package.
Configure fails with below:
configure: error: no acceptable GCJ compiler found in $PATH

This is on CentOS 7:
Linux localhost.localdomain 3.10.0-123.el7.x86_64 #1 SMP Mon Jun 30 12:09:22 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

It seems GCJ is no longer available in CentOS7.

Best regards,
Rupinder.

**Comment by bbidulock** [comment]
Use this github repository instead of the old tarball.
You can get gcj from RPMfusion or other RHEL/CentOS extra rpm sites.
