### ISSUE TITLE
Error in configure execution

### ISSUE THREAD

**Issue by danehpash** [openss7/openss7#17]
I am trying to run configure on ubunto 14.04 with linux kernel 3.13.0-71-generic version, I get the following message:

configure: | Kernel Checks |
configure: +---------------+
checking for kernel weak modules... yes
checking for kernel weak symbols... yes
checking for kernel abi support... yes
checking for kernel release... 3.13.0-71-generic
checking for kernel major release number... 3
checking for kernel minor release number... 13
checking for kernel patch release number... 0
checking for kernel extra release number... 71
checking for kernel flavor... generic
checking for kernel module/object linkage... loadable
checking for kernel compiler... gcc
checking for depmod... /sbin/depmod
checking for modprobe... /sbin/modprobe
checking for lsmod... /sbin/lsmod
checking for lsof... /usr/bin/lsof
checking for kernel modules install directory... searching
checking for for kernel modules install directory... /lib/modules/3.13.0-71-generic... yes
checking for for kernel modules install directory... /lib/modules/3.13.0-71-generic
checking for kernel modules directory... searching
checking for for kernel modules directory... /lib/modules/3.13.0-71-generic... yes
checking for for kernel modules directory... /lib/modules/3.13.0-71-generic
checking for kernel module compression... no
checking for kernel modules install subdirectory... updates/openss7
checking for kernel machine... i686
checking for kernel Ubuntu boot...
checking for kernel build directory... searching
checking for for kernel build directory... /lib/modules/3.13.0-71-generic/build... no
checking for for kernel build directory... /usr/src/kernels/3.13.0-71-generic-i686... no
checking for for kernel build directory... /usr/src/kernels/3.13.0-71-generic... no
checking for for kernel build directory... /usr/src/linux-3.13.0-71-generic-obj/i686/... no
checking for for kernel build directory... /usr/src/linux-obj... no
checking for for kernel build directory... /usr/src/kernel-headers-3.13.0-71-generic... no
checking for for kernel build directory... /usr/src/kernel-headers-3.13.0-71... no
checking for for kernel build directory... /usr/src/kernel-headers-3.13.0... no
checking for for kernel build directory... /usr/src/linux-headers-3.13.0-71-generic... no
checking for for kernel build directory... /usr/src/linux-headers-3.13.0-71... no
checking for for kernel build directory... /usr/src/linux-headers-3.13.0... no
checking for for kernel build directory... /usr/src/linux-3.13.0-71-generic... no
checking for for kernel build directory... /usr/src/linux-3.13.0-71... no
checking for for kernel build directory... /usr/src/linux-3.13.0... no
checking for for kernel build directory... /usr/src/linux-3.13... no
checking for for kernel build directory... /usr/src/linux... no
configure: error:

---

**\* This package does not support headless kernel build.  Install the
**\* appropriate built kernel-source or kernel-headers package for the
**\* target kernel "3.13.0-71-generic" and then configure again.

---

**\* The following directories do no exist in the build environment:
**\* ""
**\* "
        /lib/modules/3.13.0-71-generic/build
        /usr/src/kernels/3.13.0-71-generic-i686
        /usr/src/kernels/3.13.0-71-generic
        /usr/src/linux-3.13.0-71-generic-obj/i686/
        /usr/src/linux-obj
        /usr/src/kernel-headers-3.13.0-71-generic
        /usr/src/kernel-headers-3.13.0-71
        /usr/src/kernel-headers-3.13.0
        /usr/src/linux-headers-3.13.0-71-generic
        /usr/src/linux-headers-3.13.0-71
        /usr/src/linux-headers-3.13.0
        /usr/src/linux-3.13.0-71-generic
        /usr/src/linux-3.13.0-71
        /usr/src/linux-3.13.0
        /usr/src/linux-3.13
        /usr/src/linux"

---

**\* Check the settings of the following options before repeating:
**\*     --with-k-release 3.13.0-71-generic
**\*     --with-k-modules /lib/modules/3.13.0-71-generic
**\*     --with-k-build   3.13.0-71-generic

---

 checked my Ubuntu and found that kernel-headers for 3.13.0-71-generic are already installed, Even buildling the kernel-source did not help. Please advise me what I should do to have configure complete its execution and produce Makefile. Thanks.

Mahmoud

**Comment by danehpash** [comment]
Found the cause

**Comment by leventozen** [comment]
i got an issue that same as that.

i checked my kernel versions and packets. give me that, "already installed".

i wait for the good advises, thanks.

**Comment by bbidulock** [comment]
Ubuntu 14.04 is not supported.
