### ISSUE TITLE
Sigtran ISUP with Media gateway 

### ISSUE THREAD

**Issue by vdharashive** [openss7/openss7#2]
Hi Brian,

Can you pleae help me to understand wether it is possible to impliment following layer using Openss7.  I am very new to Openss7 stack.

Signalling  Layer
6. SIP
5- ISUP
4-M3UA
3-SCTP
2-IP
1-Ethernet

Media Layer
4. RTP for SIP
3. Media Gateway  using mgcp protocol
2. IP
1-Ethernet

Cheers!
Vinod Dharashive

**Comment by meghasemim1999** [comment]
Hi 
I still have the same issue here

can you please provide practical guidance?

i want to setup a lab as below:

SIP Phone --SIP--> SIP Server --ISUP--> Intermediate MSC --ISUP--> SIP Server --SIP--> SIP Phone
