### ISSUE TITLE
Archlinux install Issue

### ISSUE THREAD

**Issue by nahuelmatias** [openss7/openss7#20]
Hello!
I have a trouble when I'm trying to install openSS7 from AUR. 
When I execute:
[matias@arch-virtual openss7-git]$ makepkg -i

I got the following...
  GCJ      org/openss7/streams/lib_org_openss7_streams_la-Error.lo
/home/matias/Downloads/AUR/openss7-git/src/openss7-git/src/java/org/openss7/streams/SWIGTYPE_p_p_streams__Stream.java:14: error: Syntax error, annotations are only available if source level is 1.5 or greater
    protected SWIGTYPE_p_p_streams__Stream(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
                                                      ^^^^^^^^^^^^^^^^^
1 problem (1 error)
Makefile:7002: recipe for target 'org/openss7/streams/lib_org_openss7_streams_la-Error.lo' failed
make[3]: **\* [org/openss7/streams/lib_org_openss7_streams_la-Error.lo] Error 1
make[3]: Leaving directory '/home/matias/Downloads/AUR/openss7-git/src/openss7-git/src/java'
Makefile:5502: recipe for target 'all' failed
make[2]: **\* [all] Error 2
make[2]: Leaving directory '/home/matias/Downloads/AUR/openss7-git/src/openss7-git/src/java'
Makefile:19411: recipe for target 'all-recursive' failed
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory '/home/matias/Downloads/AUR/openss7-git/src/openss7-git'
Makefile:8337: recipe for target 'all' failed
make: **\* [all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

I try to compile in a 32bit environment, in VMWare.
(Linux arch-virtual 4.3.3-3-ARCH #1 SMP PREEMPT Wed Jan 20 07:44:57 CET 2016 i686 GNU/Linux)
archlinux-java status output:

Available Java environments:
  java-1.5.0-gcj-1.5.0.0/jre
  java-7-openjdk/jre (default)
If I try with the another Java environment, I get the same error. 
I don't know how to solve this, I tried to install in Debian6/7/8/CentOS6/7 and had troubles, and so, I moved to Arch. (That is a good idea, I learn a lot of this).
Thank you in advance! 
Best regards,
Matias

**Comment by bbidulock** [comment]
Fixed by commit 832ccdacc72e5511d76f13666c6335fd3cdae0ca
