### ISSUE TITLE
Issue during "makepkg -i" on Latest Arch Linux

### ISSUE THREAD

**Issue by sumeetchhetri** [openss7/openss7#24]
Hi Brian,

I am trying to install openss7 on the Latest Arch Linux, but compilation failed due to java classnotfoundexception in a lot of places, also in the documentation, there are a lot of unclosed html tags which are causing errors in javadoc generation.

uname -a
Linux SS7-AL 4.9.11-1-ARCH #1 SMP PREEMPT Sun Feb 19 13:45:52 UTC 2017 x86_64 GNU/Linux

Lot of java related errors during makepkg on Arch Linux, have attached the file with errors.

Am i doing anything wrong here?

[java-errors.txt](https://github.com/openss7/openss7/files/819633/java-errors.txt)

**Comment by alegutier** [comment]
I have compiled it in the past like this. That being said this was 3.10 RHEL7 kernel. A little different than 4.9. Set GJC to the path for openjdk

> LZMA_CMD=/usr/include/lzma \\
GCJ=`ls -l1 /etc/alternatives/java | awk '{ print $11}'` \\
./configure \\
        --enable-autotest \\
        --enable-silent-rules \\
        --disable-java \\
        --disable-docs \\
        --disable-papers-print \\
        --disable-papers-html \\
        --disable-drafts \\
        --prefix=/usr/local \\
        --without-libgcj

**Comment by sumeetchhetri** [comment]
Thanks Alexandria, I was able to compile successfully on Centos 7, reading Brian's comments about Arch Linux I thought there would be no issues with the install on Arch. I did the same with my last install though, will try this on Arch today, hopefully all goes well!

**Comment by bbidulock** [comment]
Those are warnings, not errors.  They are generated by current swig package and can be ignored.

**Comment by sumeetchhetri** [comment]
Hi Brian,

The errors actually start after the warnings,

javadoc: warning - No source files for package org.openss7.jcat
javadoc: warning - No source files for package org.openss7.tcapi
./org/openss7/ss7/mtp/JainMtpStack.java:166: error: cannot find symbol
        throws DeletedProviderException;
               ^
  symbol:   class DeletedProviderException
  location: interface JainMtpStack
./org/openss7/ss7/mtp/JainMtpStack.java:233: error: method getSignalingPointCode() is already defined in interface JainMtpStack
    public javax.jain.ss7.SignalingPointCode getSignalingPointCode()
                                             ^
./org/openss7/ss7/mtp/JainMtpListener.java:108: error: cannot find symbol
        throws jain.protocol.ss7.InvalidAddressException;
                                ^

...more errors

./javax/jain/protocol/ss7/map/position/MsPosRespEvent.java:64: error: header used out of sequence: <H4>
  * <h4>Primitive parameters:</h4> <ul>
    ^
100 errors
100 warnings
make[3]: *** [Makefile:8727: api-docs/index.html] Error 1
make[3]: Leaving directory '/home/appuser/openss7-git/src/openss7-git/src/java'
make[2]: *** [Makefile:5502: all] Error 2
make[2]: Leaving directory '/home/appuser/openss7-git/src/openss7-git/src/java'
make[1]: *** [Makefile:19411: all-recursive] Error 1
make[1]: Leaving directory '/home/appuser/openss7-git/src/openss7-git'
make: *** [Makefile:8337: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

the build fails, i guess this is due to the javadoc program not being able to find the jar files under src/java in the classpath, maybe this needs to be fixed in java.am


Thanks,
Sumeet Chhetri

**Comment by bbidulock** [comment]
I don't get this.  Which AUR package are you using?  openss7 or opness7-git?

**Comment by bbidulock** [comment]
Use openss7-git package on AUR.
