### ISSUE TITLE
Replace GCJ with OpenJDK 8/7

### ISSUE THREAD

**Issue by sumeetchhetri** [openss7/openss7#25]
Hi Brian,

As gcj is no longer available on the latest linux kernels, we should adopt the openjdk instead of gcj.

Thanks
Sumeet

**Comment by bbidulock** [comment]
Unfortunately I am using CNI.  Current version of gcj for RHEL/CentOS systems is available from RPM fusion.  For Arch, it is on the AUR and I have binary packages on unexicon.
