### ISSUE TITLE
installation Problems

### ISSUE THREAD

**Issue by hegdos** [openss7/openss7#26]
Hi Brian,

I'm having a bad day here. I follow the instructions to get the repository (sudo rpm -Uhv $REPO/$SUBDIR/openss7-repo.noarch.rpm) and I get 404 not found.

wget http://www.openss7.org/tarballs/openss7-1.1.8.8.20150415.tar.xz also returns 404 (not found)

And if I clone it from here I get stuck at ../openss7-1.1.8.8.20150415/configure --enable-autotest --enable-silent-rules (configure not found)

What am I missing? 

Best regards,

Henry

**Comment by bbidulock** [comment]
When building from git you need to execute:

    autoreconf -fiv

to generate the "configure" file.

**Comment by hegdos** [comment]
Hi Brian,
Thank you. That did it. I have another question: What flavor of Linux would
be the easiest to install on? And what Kernel Version?

Best regards,

Henry Domacasse
