### ISSUE TITLE
make error on CentOS 6.9

### ISSUE THREAD

**Issue by Olernov** [openss7/openss7#31]
src/drivers/np_ip.c: In function ‘np_ip_queue_xmit’:
src/drivers/np_ip.c:1213: error: implicit declaration of function ‘NF_HOOK_’
src/drivers/np_ip.c:1213: error: ‘dst_output_’ undeclared (first use in this function)
src/drivers/np_ip.c:1213: error: (Each undeclared identifier is reported only once
src/drivers/np_ip.c:1213: error: for each function it appears in.)
make[2]: *** [src/drivers/libOS7drivers_a-np_ip.o] Error 1

**Comment by bbidulock** [comment]
Fixed long ago.
