### ISSUE TITLE
No build CentOS 6.4

### ISSUE THREAD

**Issue by aguilasainz** [openss7/openss7#33]
Hi there! I've been trying to build the package since the last week, with no luck. I created an Arch virtual machine, but since the packages are updated, there are several issues with that, so I read here that CentOS 6.4 was the last version supported for the distro. Well, I set up a virtual machine and after installing dependencies, I stuck here: 

```
GCJ      org/openss7/streams/lib_org_openss7_streams_la-Error.lo
/home/ss7/ss7/build/src/java/./org/openss7/streams/SWIGTYPE_p_p_streams__Stream.java:14: error: Syntax error, annotations are only available if source level is 1.5
	protected SWIGTYPE_p_p_streams__Stream(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
	                                                  ^^^^^^^^^^^^^^^^^
1 problem (1 error)
make[3]: *** [org/openss7/streams/lib_org_openss7_streams_la-Error.lo] Error 1
make[3]: Leaving directory `/home/ss7/ss7/build/src/java'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/home/ss7/ss7/build/src/java'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/ss7/ss7/build'
make: *** [all] Error 2

```

I found it was solved in this commit, so I applied that patch, but no luck for me. 
 https://github.com/openss7/openss7/commit/832ccdacc72e5511d76f13666c6335fd3cdae0ca

Any ideas? Thanks!

**Comment by bbidulock** [comment]
This was fixed.
