### ISSUE TITLE
make error on Centos6.9

### ISSUE THREAD

**Issue by WhiteCloud0325** [openss7/openss7#34]
Hi,
The openss7 version which I use is openss7-1.1.7.20131207.tar.xz built on Centos 6.9. I have installed all additional prerequisites and ran ../openss7-1.1.8.8.20150415/configure --enable-autotest --enable-silent-rules successfully. But when I make V=0, there are some errors:
make[3]: *** [openss7.txt]  error 127
make[3]: Leaving directory `/home/*/workspace/build/doc/manual'
make[2]: *** [doc/manual/openss7.txt] error 2
make[2]: Leaving directory `/home/*/workspace/build'
make[1]: *** [all-recursive] error 1
make[1]: Leaving directory `/home/*/workspace/build'
make: *** [all] error 2
I can't found openss7.txt at /home/*/workspace/build/doc/manual and  openss7-1.1.7.20131207
Any ideas? Thanks

**Comment by bbidulock** [comment]
Insufficient information.
