### ISSUE TITLE
No rule to make target 'specfs.mod.c', needed by 'stamp-mobjects

### ISSUE THREAD

**Issue by 5l1v3r1** [openss7/openss7#40]
make -j3
make  all-recursive
make[1]: Entering directory '/media/root/KALI4/openss7-master'
Making all in src
make[2]: Entering directory '/media/root/KALI4/openss7-master/src'
make  all-recursive
make[3]: Entering directory '/media/root/KALI4/openss7-master/src'
Making all in include
make[4]: Entering directory '/media/root/KALI4/openss7-master/src/include'
make  all-am
make[5]: Entering directory '/media/root/KALI4/openss7-master/src/include'
make[5]: Nothing to be done for 'all-am'.
make[5]: Leaving directory '/media/root/KALI4/openss7-master/src/include'
make[4]: Leaving directory '/media/root/KALI4/openss7-master/src/include'
make[4]: Entering directory '/media/root/KALI4/openss7-master/src'
make[4]: Nothing to be done for 'all-am'.
make[4]: Leaving directory '/media/root/KALI4/openss7-master/src'
make[3]: Leaving directory '/media/root/KALI4/openss7-master/src'
make[2]: Leaving directory '/media/root/KALI4/openss7-master/src'
Making all in po
make[2]: Entering directory '/media/root/KALI4/openss7-master/po'
test ! -f ./openss7.pot || \
  test -z "de.gmo" || make de.gmo
make[3]: Entering directory '/media/root/KALI4/openss7-master/po'
/usr/bin/msgmerge --update  --lang=de de.po openss7.pot
............................... bitti.
make[3]: Leaving directory '/media/root/KALI4/openss7-master/po'
touch stamp-po
make[2]: Leaving directory '/media/root/KALI4/openss7-master/po'
Making all in .
make[2]: Entering directory '/media/root/KALI4/openss7-master'
  GEN      src/include/sys/config.h
  GEN      src/include/sys/modconf.h
  CC       libcdiapi_la-pthread.lo
  CC       libcdiapi_la-cdiapi.lo
  CC       libdlpiapi_la-pthread.lo
  CC       libdlpiapi_la-dlpiapi.lo
  CC       libnpiapi_la-pthread.lo
  CC       libnpiapi_la-npiapi.lo
  CC       libdlpi_la-pthread.lo
  CC       libdlpi_la-dlpi.lo
  CC       inetaddr_la-netdir_inet.lo
  CC       libsx25_la-padent.lo
  CC       libsx25_la-x25config.lo
  CC       libsx25_la-xhostent.lo
  CC       strMIB_la-strMIB.lo
  CC       strMIB_la-strExtMIB.lo
  CC       mxMIB_la-ds0Bundle.lo
  CC       mxMIB_la-ds0.lo
  CC       mxMIB_la-ds1EXT.lo
  CC       mxMIB_la-mxMIB.lo
  CC       mxMIB_la-phyMIB.lo
  CC       ss7MIB_la-ss7MIB.lo
  CC       ss7MIB_la-mtpMIB.lo
  CC       ss7MIB_la-mtpOmMIB.lo
  CC       ss7MIB_la-sccpMIB.lo
  CC       ss7MIB_la-sccpOmMIB.lo
  CC       ss7MIB_la-tcapMIB.lo
  CC       ss7MIB_la-tcapOmMIB.lo
  GEN      README-make
  GEN      INSTALL-openss7
  GEN      LSM
  GEN      openss7-1.1.8.20200317.lsm
  GEN      MANUAL
make[3]: Entering directory '/media/root/KALI4/openss7-master/doc/manual'
  GEN      .deps/info.Pd
  GEN      openss7.txt
  GEN      .version
make[2]: *** No rule to make target 'specfs.mod.c', needed by 'stamp-mobjects'. Durdu.
make[2]: *** Bitmemiş işler için bekliyor....
  KCPP   specfs.ver
  KCPP   streams.ver
  KCPP   nit_if.ver
  KCPP   bpf.ver
  KCPP   clone.ver
  KCPP   sth.ver
  KCPP   aixcompat.ver
  KCPP   hpuxcompat.ver
  KCPP   irixcompat.ver
  KCPP   maccompat.ver
  KCPP   mpscompat.ver
  KCPP   os7compat.ver
  KCPP   osfcompat.ver
  KCPP   suncompat.ver
  KCPP   svr3compat.ver
  KCPP   svr4compat.ver
  KCPP   uw7compat.ver
  KCPP   wrapper.ver
make[3]: Leaving directory '/media/root/KALI4/openss7-master/doc/manual'
  GEN      MANUAL
make[2]: Leaving directory '/media/root/KALI4/openss7-master'
make[1]: *** [Makefile:20008: all-recursive] Error 1
make[1]: Leaving directory '/media/root/KALI4/openss7-master'
make: *** [Makefile:8928: all] Error 2

**Comment by bbidulock** [comment]
parallel build (make -j3) never works on openss7

use make -j1
