### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by johntaves** [openss7/openss7#8]
I tried to register @ http://www.openss7.org/repos.html but keep getting "Street is invalid. Please provide your full street address." (I tried putting something in every field including "unit" and "fax" even though I have no "unit" or "fax", but still I get that error).

**Comment by bbidulock** [comment]
$address_street !~ /^(([A-Z][-a-z0-9]*(\.)?|[-0-9 #]+)(\s+)?)+$/

A street address that passes that regex will do.
