### ISSUE TITLE
ubuntu 14.04 fails

### ISSUE THREAD

**Issue by johntaves** [openss7/openss7#9]
I made a clean ubuntu 14.04. I have installed kernel sources.

I get the message:

The following directories do not exist in the build environment:

/lib/modules/3.13.0-32-generic/build
/usr/src/kernels/...
etc...

Some of these directories do exist. I assume you are not looking for all of them, but rather some subset. It is not obvious what subset you are looking for but as far as I can tell the directories you are looking for exist.

I am trying to get openss7 to install on anything. I wanted to prove this actually works on something before I spend more time on the 2.6.12 kernel.

**Comment by bbidulock** [comment]
Ubuntu 14.04 is not in the supported list.  See [MANUAL](/openss7/openss7/blob/master/MANUAL) at about line 3853.

**Comment by ferrerogonzalo** [comment]
Hi, I had the same trouble with Ubuntu 12.04. It hasn't recognized the linux headers. It seems as the same trouble that had VMware installation, where the version file of the kernel was moved and thats why it does'n detect the headers. The next line worked for me:

sudo ln -s /usr/src/linux-headers-$(uname -r)/include/generated/uapi/linux/version.h /usr/src/linux-headers-$(uname -r)/include/linux/version.h 

Regards :)
